syntax = "proto3";

package driftstore;

enum NodeStatus {
    UP = 0;
    REMOVED = 1;
}

enum WriteOutcome {
    STORED = 0;
    ALREADY_CURRENT = 1;
}

message MembershipEntry {
    string writer_id = 1;
    string address = 2;
    NodeStatus status = 3;
    repeated uint64 tokens = 4;
    int64 last_updated = 5;
}

message MembershipTable {
    map<string, MembershipEntry> entries = 1;
}

message VectorClock {
    map<string, uint64> counters = 1; // <node_id, node's counter for the key>
    int64 last_updated = 2; // per LWW input only (stamped by the coordinating node)
    string writer_id = 3;
}

service DriftStoreNode {
    rpc Ping(PingRequest) returns (PingResponse);
    rpc GossipExchange(GossipRequest) returns (GossipResponse);
    rpc GetStatus(StatusRequest) returns (StatusResponse);
    rpc RemoveNode(RemoveRequest) returns (RemoveResponse);
    rpc Put(PutRequest) returns (PutResponse);
    rpc Get(GetRequest) returns (GetResponse);
    rpc ReplicateWrite(ReplicateWriteRequest) returns (ReplicateWriteResponse);
    rpc ReplicateRead(ReplicateReadRequest) returns (ReplicateReadResponse);
}

message PutRequest {
    string key = 1;
    string value = 2;
    VectorClock context = 3; // this is optional: abset means blind write
}

message PutResponse {
    bool success = 1; // this is only on if acks >= W
    int32 acks = 2; // how many replicas succeeded ( >= W )
    VectorClock context = 3;
}

message GetRequest {
    string key = 1;
}

message GetResponse {
    bool found = 1;
    string value = 2;
    int32 responses = 3; // number of replicas answered ( >= R )
    VectorClock context = 4;
}

message ReplicateWriteRequest {
    string key = 1;
    string value = 2;
    VectorClock vector_clock = 3;
}

message ReplicateWriteResponse {
    bool success = 1;
    WriteOutcome outcome = 2; // observability ONLY
}

message ReplicateReadRequest {
    string key = 1;
}

message ReplicateReadResponse {
    bool found = 1;
    string value = 2;
    VectorClock vector_clock = 3;
}

message PingRequest {
    string sender_node_id = 1;
}

message PingResponse {
    string responder_node_id = 1;
}

message GossipRequest {
    string sender_node_id = 1;
    MembershipTable table = 2; // push
}

message GossipResponse {
    string responder_node_id = 1;
    MembershipTable table = 2; // pull (in the same RT)
}

message StatusRequest {}

message StatusResponse {
    string node_id = 1;
    string table_dump = 2;
    string ring_dump = 3;
}

message RemoveRequest {
    string removed_node_id = 1;
}

message RemoveResponse {
    bool accepted = 1; // false if target_node_id is NOT in the table
}

